import type { Product } from '../types';
import { CHARACTER_GUIDES } from '../categories';

/**
 * Source: Dashrize-Products/CHARACTER-GUIDES/3 - LISTING TEXT/listing-copy-paste.md
 *
 * Forty individual guides (₹499 each) plus the 40-guide set, "The Character
 * Codex" (₹2,999). Every guide is unofficial commentary about a fictional
 * character: no artwork, dialogue or story content is reproduced.
 *
 * None of these guides ship a cover image — only the set does (per the
 * listing file: "`1-cover-thumbnail.png` is the codex cover"). Their
 * `gallery` is deliberately `[]`; the storefront renders a typographic
 * fallback card for any product with no cover, see components/product/CoverFallback.tsx.
 *
 * Per-guide copy: title is exactly the filename with dashes turned to
 * spaces (the listing file's own rule), and `tagline` fills the file's
 * "Short description template" with that guide's "Ready-made hook" from
 * its table — both used verbatim, nothing paraphrased. The FAQ and
 * disclaimer are the family's own approved text, shared verbatim across
 * every listing in the family (the codex and all forty guides), since nothing
 * in that text is bundle-specific — it describes the guide format itself.
 *
 * `longDescription` and `bulletPoints` are left empty for the individual
 * guides: the listing file gives no per-guide long-form copy, only the hook
 * + short-description template captured in `tagline`. Inventing more would
 * be fabrication. The set carries the family's real long description,
 * transcribed verbatim from the listing file's fenced block.
 *
 * `pageCount: 20` / `trackerCount: 3` per guide is the listing file's own
 * stated fact ("Every guide is 20 designed pages with 3 printable sheets"),
 * not an estimate. The set's totals (800 / 120) are the same fact × 40,
 * exactly as the listing file states them.
 */

const CHARACTER_GUIDE_FAQS = [
    { question: 'Is this official / licensed?', answer: 'No, and it says so on every page. It is independent commentary about fictional characters. No artwork, dialogue or story content is reproduced — everything in it is original.' },
    { question: 'How long is each guide?', answer: '20 designed pages, including 3 printable sheets. 800 pages across the bundle.' },
    { question: 'Will this make me like the character?', answer: 'No. That is the entire premise. Each guide separates what is real from what is drawn, and tells you plainly what the real version actually gets you.' },
    { question: 'Can I buy just one?', answer: 'Yes, each is listed separately at ₹499.' },
    { question: 'Which one should I start with?', answer: 'Saitama. It is the funniest and the most honest, and it undercuts half the others.' },
    { question: 'Is the fitness stuff safe?', answer: 'The guides say to consult a doctor, never train through sharp pain, and never copy the fictional training loads. The Rocky guide is explicit about head injury; the Baki guide is explicit about training through injury.' },
    { question: 'Are the anime ones and the film ones the same format?', answer: 'Identical. Same twenty-page spine, same real-versus-drawn table, same three printable sheets — whether the character is from Naruto, Suits, Lagaan or Chak De! India.' },
  ];

const CHARACTER_GUIDE_DISCLAIMER = 'Unofficial, independent commentary. All characters named are fictional and are owned by their respective rights holders. These guides are not endorsed by, affiliated with, licensed by or connected to those rights holders, and reproduce no artwork, dialogue or story content — all text and illustration is original. Nothing here is medical, psychological, legal, financial, career or scientific advice, and no outcome of any kind is promised. General information for healthy adults. Consult a doctor before beginning any training programme. If you are struggling — with anger, pressure, low mood or thoughts of harming yourself — please speak to someone. In India, Tele-MANAS is free and confidential on 14416.';

const CHARACTER_GUIDE_HELPLINES = [
    { name: 'Tele-MANAS', number: '14416', context: 'If you are struggling with anger, pressure, low mood or thoughts of harming yourself, please speak to someone. Tele-MANAS is free and confidential.' },
  ];

export const howToBeLikeAndyDufresne: Product = {
  slug: 'how-to-be-like-andy-dufresne',
  title: 'How to be like Andy Dufresne',
  tagline: 'One letter a week. Then two. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'andy dufresne'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Andy-Dufresne.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeAtticusFinch: Product = {
  slug: 'how-to-be-like-atticus-finch',
  title: 'How to be like Atticus Finch',
  tagline: 'The decency is real. The rest deserves the argument it now gets. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'atticus finch'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Atticus-Finch.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeBakiHanma: Product = {
  slug: 'how-to-be-like-baki-hanma',
  title: 'How to be like Baki Hanma',
  tagline: 'The obsession is real. The training is not. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'baki hanma'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Baki-Hanma.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeBhuvan: Product = {
  slug: 'how-to-be-like-bhuvan',
  title: 'How to be like Bhuvan',
  tagline: 'Name the terms. Then build the side nobody else was bidding for. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'bhuvan'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Bhuvan.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeBruceWayne: Product = {
  slug: 'how-to-be-like-bruce-wayne',
  title: 'How to be like Bruce Wayne',
  tagline: 'Always be the one who prepared. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'bruce wayne'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Bruce-Wayne.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeEdwardElric: Product = {
  slug: 'how-to-be-like-edward-elric',
  title: 'How to be like Edward Elric',
  tagline: 'Everything costs something. Decide in advance what you are paying. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'edward elric'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Edward-Elric.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeForrestGump: Product = {
  slug: 'how-to-be-like-forrest-gump',
  title: 'How to be like Forrest Gump',
  tagline: 'Do the next plain thing. Then do it again for eleven months. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'forrest gump'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Forrest-Gump.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeGojoSatoru: Product = {
  slug: 'how-to-be-like-gojo-satoru',
  title: 'How to be like Gojo Satoru',
  tagline: 'Everyone copies the swagger. Nobody copies what pays for it. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'gojo satoru'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Gojo-Satoru.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeGoku: Product = {
  slug: 'how-to-be-like-goku',
  title: 'How to be like Goku',
  tagline: 'He trains because he enjoys it. That is not a detail — it is the method. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'goku'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Goku.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeGuts: Product = {
  slug: 'how-to-be-like-guts',
  title: 'How to be like Guts',
  tagline: 'Carrying it and being fine are not the same thing. Both are in here. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'guts'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Guts.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeHarveySpecter: Product = {
  slug: 'how-to-be-like-harvey-specter',
  title: 'How to be like Harvey Specter',
  tagline: 'Nobody ever won a room with a comeback. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'harvey specter'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Harvey-Specter.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeHermioneGranger: Product = {
  slug: 'how-to-be-like-hermione-granger',
  title: 'How to be like Hermione Granger',
  tagline: 'She is not the clever one. She is the one who did the reading. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'hermione granger'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Hermione-Granger.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeIqbal: Product = {
  slug: 'how-to-be-like-iqbal',
  title: 'How to be like Iqbal',
  tagline: 'No facility, no coach, no permission. One action, a thousand times. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'iqbal'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Iqbal.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeKabirKhan: Product = {
  slug: 'how-to-be-like-kabir-khan',
  title: 'How to be like Kabir Khan',
  tagline: 'Change what gets counted and the team changes within a fortnight. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'kabir khan'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Kabir-Khan.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeKakashiHatake: Product = {
  slug: 'how-to-be-like-kakashi-hatake',
  title: 'How to be like Kakashi Hatake',
  tagline: 'The strongest person in the room is almost never the loudest one in it. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'kakashi hatake'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Kakashi-Hatake.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeKilluaZoldyck: Product = {
  slug: 'how-to-be-like-killua-zoldyck',
  title: 'How to be like Killua Zoldyck',
  tagline: 'The hardest thing he does is stop being what he was trained into. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'killua zoldyck'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Killua-Zoldyck.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeL: Product = {
  slug: 'how-to-be-like-l',
  title: 'How to be like L',
  tagline: 'Stop saying "I think". Start saying "seventy per cent, because —". 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'l'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-L.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeLeviAckerman: Product = {
  slug: 'how-to-be-like-levi-ackerman',
  title: 'How to be like Levi Ackerman',
  tagline: 'The standard does not drop because nobody is watching. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'levi ackerman'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Levi-Ackerman.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeMichaelScofield: Product = {
  slug: 'how-to-be-like-michael-scofield',
  title: 'How to be like Michael Scofield',
  tagline: 'Plan it backwards from the end, then assume three steps fail. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'michael scofield'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Michael-Scofield.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeMob: Product = {
  slug: 'how-to-be-like-mob',
  title: 'How to be like Mob',
  tagline: 'The strongest thing in the show is the part he refuses to use. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'mob'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Mob.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeNarutoUzumaki: Product = {
  slug: 'how-to-be-like-naruto-uzumaki',
  title: 'How to be like Naruto Uzumaki',
  tagline: 'Nobody backed him either. This is what he did with the years before they did. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'naruto uzumaki'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Naruto-Uzumaki.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikePatrickJane: Product = {
  slug: 'how-to-be-like-patrick-jane',
  title: 'How to be like Patrick Jane',
  tagline: 'He is not reading you. You are telling him. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'patrick jane'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Patrick-Jane.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikePeterParker: Product = {
  slug: 'how-to-be-like-peter-parker',
  title: 'How to be like Peter Parker',
  tagline: 'Telling nobody is not noble. It is the mistake. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'peter parker'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Peter-Parker.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeRancho: Product = {
  slug: 'how-to-be-like-rancho',
  title: 'How to be like Rancho',
  tagline: 'If you cannot say it plainly, you memorised a label. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'rancho'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Rancho.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeRockLee: Product = {
  slug: 'how-to-be-like-rock-lee',
  title: 'How to be like Rock Lee',
  tagline: 'No talent. So what. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'rock lee'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Rock-Lee.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeRocketSingh: Product = {
  slug: 'how-to-be-like-rocket-singh',
  title: 'How to be like Rocket Singh',
  tagline: 'Everyone wins the pitch. Almost nobody survives the follow-up. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'rocket singh'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Rocket-Singh.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeRockyBalboa: Product = {
  slug: 'how-to-be-like-rocky-balboa',
  title: 'How to be like Rocky Balboa',
  tagline: 'He loses the first one, and that is the point. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'rocky balboa'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Rocky-Balboa.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeRoronoaZoro: Product = {
  slug: 'how-to-be-like-roronoa-zoro',
  title: 'How to be like Roronoa Zoro',
  tagline: 'He lost. Then he trained. That week is the whole character. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'roronoa zoro'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Roronoa-Zoro.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeSaitama: Product = {
  slug: 'how-to-be-like-saitama',
  title: 'How to be like Saitama',
  tagline: 'The only routine in fiction that actually works — and it is boring on purpose. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  featured: true,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'saitama'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Saitama.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeSenkuIshigami: Product = {
  slug: 'how-to-be-like-senku-ishigami',
  title: 'How to be like Senku Ishigami',
  tagline: 'Ask what it needs. Then ask again, until the answer fits in one evening. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'senku ishigami'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Senku-Ishigami.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeSherlockHolmes: Product = {
  slug: 'how-to-be-like-sherlock-holmes',
  title: 'How to be like Sherlock Holmes',
  tagline: 'You see. You do not observe. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'sherlock holmes'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Sherlock-Holmes.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeShikamaruNara: Product = {
  slug: 'how-to-be-like-shikamaru-nara',
  title: 'How to be like Shikamaru Nara',
  tagline: 'Lazy people find the shortest correct path. That is a skill, not a flaw. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'shikamaru nara'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Shikamaru-Nara.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeSteveRogers: Product = {
  slug: 'how-to-be-like-steve-rogers',
  title: 'How to be like Steve Rogers',
  tagline: 'Be the same person when the incentives change. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'steve rogers'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Steve-Rogers.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeTanjiroKamado: Product = {
  slug: 'how-to-be-like-tanjiro-kamado',
  title: 'How to be like Tanjiro Kamado',
  tagline: 'Kind is a decision you make on the days you are tired. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'tanjiro kamado'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Tanjiro-Kamado.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeTedLasso: Product = {
  slug: 'how-to-be-like-ted-lasso',
  title: 'How to be like Ted Lasso',
  tagline: 'Be curious, not sure. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'ted lasso'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Ted-Lasso.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeThomasShelby: Product = {
  slug: 'how-to-be-like-thomas-shelby',
  title: 'How to be like Thomas Shelby',
  tagline: 'Three moves ahead — and everything the show says it costs. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'thomas shelby'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Thomas-Shelby.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeThorfinn: Product = {
  slug: 'how-to-be-like-thorfinn',
  title: 'How to be like Thorfinn',
  tagline: 'The half everyone skips is the half worth copying. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'thorfinn'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Thorfinn.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeTonyStark: Product = {
  slug: 'how-to-be-like-tony-stark',
  title: 'How to be like Tony Stark',
  tagline: 'The first suit was rubbish. That is the lesson. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'tony stark'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Tony-Stark.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeTyrionLannister: Product = {
  slug: 'how-to-be-like-tyrion-lannister',
  title: 'How to be like Tyrion Lannister',
  tagline: 'When you have no strength, know things. That is the whole position. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'tyrion lannister'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Tyrion-Lannister.pdf'],
  setSlug: 'the-character-codex',
};

export const howToBeLikeVegeta: Product = {
  slug: 'how-to-be-like-vegeta',
  title: 'How to be like Vegeta',
  tagline: 'The rival is useful. The resentment is not. Separate them. 20 pages: what is real, what is fiction, four traits that transfer with worked examples, the daily and weekly stack, what NOT to copy, and three printable sheets. Unofficial commentary.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'vegeta'],
  gallery: [],
  deliveryFiles: ['How-to-be-like-Vegeta.pdf'],
  setSlug: 'the-character-codex',
};

export const characterGuides: Product[] = [
  howToBeLikeAndyDufresne,
  howToBeLikeAtticusFinch,
  howToBeLikeBakiHanma,
  howToBeLikeBhuvan,
  howToBeLikeBruceWayne,
  howToBeLikeEdwardElric,
  howToBeLikeForrestGump,
  howToBeLikeGojoSatoru,
  howToBeLikeGoku,
  howToBeLikeGuts,
  howToBeLikeHarveySpecter,
  howToBeLikeHermioneGranger,
  howToBeLikeIqbal,
  howToBeLikeKabirKhan,
  howToBeLikeKakashiHatake,
  howToBeLikeKilluaZoldyck,
  howToBeLikeL,
  howToBeLikeLeviAckerman,
  howToBeLikeMichaelScofield,
  howToBeLikeMob,
  howToBeLikeNarutoUzumaki,
  howToBeLikePatrickJane,
  howToBeLikePeterParker,
  howToBeLikeRancho,
  howToBeLikeRockLee,
  howToBeLikeRocketSingh,
  howToBeLikeRockyBalboa,
  howToBeLikeRoronoaZoro,
  howToBeLikeSaitama,
  howToBeLikeSenkuIshigami,
  howToBeLikeSherlockHolmes,
  howToBeLikeShikamaruNara,
  howToBeLikeSteveRogers,
  howToBeLikeTanjiroKamado,
  howToBeLikeTedLasso,
  howToBeLikeThomasShelby,
  howToBeLikeThorfinn,
  howToBeLikeTonyStark,
  howToBeLikeTyrionLannister,
  howToBeLikeVegeta,
];

export const theCharacterCodex: Product = {
  slug: 'the-character-codex',
  title: 'The Character Codex — 40 Guides, 800 Pages',
  tagline: 'Forty characters, split honestly: what you can actually build, what is fiction, and what a season of the real version gets you. 800 designed pages, 40 guides, 120 printable sheets. One payment, lifetime access.',
  price: 2999,
  anchorPrice: 19960,
  pageCount: 800,
  trackerCount: 120,
  accent: CHARACTER_GUIDES.accent,
  category: CHARACTER_GUIDES,
  format: 'PDF',
  fileCount: 2,
  longDescription: [
    {
      heading: 'EVERY "TRAIN LIKE BAKI" VIDEO SKIPS THE SAME PAGE',
      paragraphs: [
        'The one where somebody tells you which parts are drawn.',
        'You cannot copy a character whose feats are illustrated. You can copy the thing underneath them — and for most of these characters, the thing underneath is genuinely good and nobody has ever written it down properly.',
        'So every guide in this pack is built the same way, over twenty pages. What is real and what is fiction, in a straight table. The myth the character creates, and why it is wrong. Four traits that actually transfer — each one with the mechanism, and then a named worked example of a real person building it. A daily stack and a weekly stack. Six situations where it comes up. The protocol. What NOT to copy. Troubleshooting for when it stops working. The honest limits. And three printable sheets, because the sheets are the part that changes anything.',
      ],
    },
    {
      heading: 'WHAT IS IN IT — 40 GUIDES, 20 PAGES EACH, 800 PAGES TOTAL',
      paragraphs: [
        'Training and consistency — Baki Hanma, Saitama, Rock Lee, Rocky Balboa, Goku, Vegeta, Iqbal',
        'Standards and discipline — Levi Ackerman, Roronoa Zoro, Bruce Wayne, Thorfinn, Guts',
        'Thinking and attention — L, Sherlock Holmes, Senku Ishigami, Michael Scofield, Shikamaru Nara, Edward Elric',
        'Studying and preparation — Rancho, Hermione Granger, L',
        'Building and shipping — Tony Stark, Andy Dufresne, Rocket Singh, Bhuvan',
        'The room — Harvey Specter, Thomas Shelby, Gojo Satoru, Tyrion Lannister',
        'Leading a group — Ted Lasso, Kabir Khan, Kakashi Hatake',
        'Reading people — Patrick Jane, Sherlock Holmes',
        'When it is heavy — Tanjiro Kamado, Mob, Guts, Thorfinn',
        'When nobody is backing you — Naruto Uzumaki, Forrest Gump, Peter Parker, Iqbal',
        'Holding a line — Steve Rogers, Atticus Finch, Killua Zoldyck',
      ],
    },
    {
      heading: 'A FEW OF THE ACTUAL ANSWERS',
      paragraphs: [
        'Saitama\'s routine is the only training programme in fiction that is real. It is also deliberately boring, which is the joke and the whole method.',
        'Rocky loses the fight in the first film, and the film treats it as a total success — because he set a goal he controlled. That is the most useful idea in the pack.',
        'Patrick Jane\'s cold reading is a documented technique used on real people for money in every city in India. The guide teaches it so you can spot it being run on you.',
        'Batman\'s four-hour sleep schedule is the most-copied and most-wrong thing in comics. It degrades exactly the capabilities the character is admired for.',
        'Andy Dufresne\'s escape is not the lesson. One letter a week for six years, then two a week, is the lesson.',
        'Peter Parker\'s secrecy is written as nobility and it is actually the flaw — telling nobody is what makes almost everything else in that character\'s life fail.',
        'Rocket Singh builds his company inside his employer\'s office, and that is the one part of the film the guide tells you plainly not to copy.',
        'Rancho is right that understanding beats memorising — and the film quietly skips the part where you still have to do the past papers. The guide puts it back.',
      ],
    },
    {
      heading: 'WHAT THESE ARE NOT',
      paragraphs: [
        'Not official. Not affiliated with anyone. No character artwork, no dialogue, no story content — every page, every diagram and every cover in this pack is original work. It is independent commentary about fictional characters, which is exactly what it says on each one.',
        'And no promises. Several of these characters do things that would injure or imprison a real person, and every guide has a page called WHAT NOT TO COPY instead of pretending otherwise. That honesty is the format, not a disclaimer bolted on the end.',
      ],
    },
  ],
  bulletPoints: [
    '40 guides, 20 designed pages each, 800 pages total',
    '120 printable sheets across the pack',
    'A real-vs-fiction table, four transferable traits and a worked example, in every guide',
    'A daily stack and a weekly stack in every guide',
    'A page of what NOT to copy in every guide',
    'Unofficial commentary — no artwork, dialogue or story content reproduced',
    'Instant download · One payment · Lifetime access',
  ],
  faqs: CHARACTER_GUIDE_FAQS,
  disclaimer: CHARACTER_GUIDE_DISCLAIMER,
  helplines: CHARACTER_GUIDE_HELPLINES,
  tags: ['character guides', 'unofficial commentary', 'the character codex'],
  gallery: [
    {
      filename: '1-cover-thumbnail.png',
      role: 'cover',
      alt: 'The Character Codex cover: forty characters, one honest pack.',
    },
  ],
  deliveryFiles: ['The-Character-Codex.zip', 'START-HERE.txt'],
};

/** All forty individual guides plus the Character Codex set, in filename order. */
export const allCharacterGuideProducts: Product[] = [...characterGuides, theCharacterCodex];
