import type { Product } from '../types';
import { THE_TEN_SERIES } from '../categories';

/**
 * Source: Dashrize-Products/THE-TEN-SERIES/3 - LISTING TEXT/listing-copy-paste.md
 *
 * Twenty-three individual guides (₹499 each) plus the 23-guide set (₹2,999).
 * Each guide takes one over-used Instagram hook ("dangerously disciplined",
 * "hard to kill"...) and gives the real number and method behind it instead
 * of the 30-day version.
 *
 * This family's listing file gives an explicit "Title" column for all 23
 * individuals (not just a hook), so `title` uses that column verbatim
 * rather than the filename — one guide's real title carries an apostrophe
 * ("...Before You're 25") that the filename itself can't ("...Youre-25",
 * a filesystem constraint, not the approved title).
 *
 * None of these guides ship a cover image — only the set does. Their
 * `gallery` is deliberately `[]`; see components/product/CoverFallback.tsx.
 *
 * `tagline` fills this family's own short-description template with each
 * guide's hook, exactly as given. `longDescription` and `bulletPoints` stay
 * empty for individuals (no per-guide long-form copy exists); the set's
 * long description is transcribed verbatim from the listing file.
 *
 * This is the one family whose disclaimer carries no helpline number (the
 * approved text names none), so `helplines: []` here is the same
 * don't-invent-a-number precedent already set by lib/catalog/products/money-os.ts.
 */

const TEN_SERIES_FAQS = [
    { question: 'How long is each guide?', answer: '20 designed pages including 3 printable sheets. 460 pages across the full set.' },
    { question: 'Is this generic motivational content?', answer: 'The opposite. Every guide has a page called WHAT NOT TO DO, an honest-limits page, and it names the popular claims in its subject that do not hold up.' },
    { question: 'Can I buy just one?', answer: 'Yes, each is listed separately at ₹499 — or all 23 for ₹2,999.' },
    { question: 'Which should I start with?', answer: 'What Your Screentime Costs You. It starts with a seven-day audit you can do without changing anything, and it makes the other twenty-two feel urgent.' },
    { question: 'Is any of this advice?', answer: 'No. It is general information for adults, and every guide says so. Nothing here is medical, psychological, legal, financial or career advice, and no outcome is promised.' },
  ];

const TEN_SERIES_DISCLAIMER = 'General information for adults. Nothing here is medical, psychological, legal, financial, investment, educational or career advice; no product, insurer, scheme, app, course, employer or platform is named or endorsed; and no outcome of any kind is claimed or implied. Figures are approximate ranges from public sources, and where a figure is illustrative the page says so. Worked examples are composites written to show a method, not real people. Consult a doctor before changing how you train, eat or medicate, and a qualified professional for anything financial or legal.';

export const guide10MoneyHabitsThatActuallyCompound: Product = {
  slug: '10-money-habits-that-actually-compound',
  title: '10 Money Habits That Actually Compound',
  tagline: 'No tips, no products, no returns promised. Just the order. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Money-Habits-That-Actually-Compound.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10ThingsBodyLanguageActuallyTellsYou: Product = {
  slug: '10-things-body-language-actually-tells-you',
  title: '10 Things Body Language Actually Tells You',
  tagline: 'Crossed arms means cold. Here is the small amount that is real. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Things-Body-Language-Actually-Tells-You.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToActuallyBecomeAnEarlyRiser: Product = {
  slug: '10-ways-to-actually-become-an-early-riser',
  title: '10 Ways to Actually Become an Early Riser',
  tagline: 'A clock problem, not a willpower problem. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Actually-Become-an-Early-Riser.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeDangerouslyDisciplined: Product = {
  slug: '10-ways-to-be-dangerously-disciplined',
  title: '10 Ways to Be Dangerously Disciplined',
  tagline: 'You do not have a willpower problem. You have a decision problem. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Dangerously-Disciplined.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeDangerouslyHardToKill: Product = {
  slug: '10-ways-to-be-dangerously-hard-to-kill',
  title: '10 Ways to Be Dangerously Hard to Kill',
  tagline: 'It is not fighting. It is a helmet, a blood test and seven hours. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Dangerously-Hard-to-Kill.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeDangerouslyLikeable: Product = {
  slug: '10-ways-to-be-dangerously-likeable',
  title: '10 Ways to Be Dangerously Likeable',
  tagline: 'Charismatic people are not more interesting. They are more interested. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Dangerously-Likeable.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeDangerouslySmart: Product = {
  slug: '10-ways-to-be-dangerously-smart',
  title: '10 Ways to Be Dangerously Smart',
  tagline: 'Being wrong less expensively, and finding out sooner. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Dangerously-Smart.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeDangerouslyUnbothered: Product = {
  slug: '10-ways-to-be-dangerously-unbothered',
  title: '10 Ways to Be Dangerously Unbothered',
  tagline: 'Not feeling nothing. Feeling it and not being run by it. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Dangerously-Unbothered.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeGoodAtBeingAlone: Product = {
  slug: '10-ways-to-be-good-at-being-alone',
  title: '10 Ways to Be Good at Being Alone',
  tagline: 'Solitude makes you stronger. Isolation costs you your health. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Good-at-Being-Alone.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeImpossibleToManipulate: Product = {
  slug: '10-ways-to-be-impossible-to-manipulate',
  title: '10 Ways to Be Impossible to Manipulate',
  tagline: 'It does not attack your intelligence. It attacks urgency. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Impossible-to-Manipulate.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeTakenSeriouslyBeforeYoure25: Product = {
  slug: '10-ways-to-be-taken-seriously-before-youre-25',
  title: '10 Ways to Be Taken Seriously Before You\'re 25',
  tagline: 'Being young is not the problem. Being unverifiable is. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Taken-Seriously-Before-Youre-25.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBeUnforgettableInSixtySeconds: Product = {
  slug: '10-ways-to-be-unforgettable-in-sixty-seconds',
  title: '10 Ways to Be Unforgettable in Sixty Seconds',
  tagline: 'People decide fast — and they revise. Here is what actually lasts. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Be-Unforgettable-in-Sixty-Seconds.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToBuildConfidenceThatIsReal: Product = {
  slug: '10-ways-to-build-confidence-that-is-real',
  title: '10 Ways to Build Confidence That Is Real',
  tagline: 'Confidence follows evidence. So go and manufacture evidence. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Build-Confidence-That-Is-Real.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToGetDangerouslyLucky: Product = {
  slug: '10-ways-to-get-dangerously-lucky',
  title: '10 Ways to Get Dangerously Lucky',
  tagline: 'You cannot make luck. You can change how much can reach you. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Get-Dangerously-Lucky.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToHaveADangerouslyGoodMemory: Product = {
  slug: '10-ways-to-have-a-dangerously-good-memory',
  title: '10 Ways to Have a Dangerously Good Memory',
  tagline: 'You do not have a bad memory. You have an ordinary one, used badly. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Have-a-Dangerously-Good-Memory.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToLearnAnythingFaster: Product = {
  slug: '10-ways-to-learn-anything-faster',
  title: '10 Ways to Learn Anything Faster',
  tagline: 'The methods that work feel worse while you are doing them. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Learn-Anything-Faster.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToNeverLoseYourTemper: Product = {
  slug: '10-ways-to-never-lose-your-temper',
  title: '10 Ways to Never Lose Your Temper',
  tagline: 'The anger is not the problem. The next four seconds are. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Never-Lose-Your-Temper.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToReadPeople: Product = {
  slug: '10-ways-to-read-people',
  title: '10 Ways to Read People',
  tagline: 'You cannot detect lies from a face. Here is what you can actually read. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Read-People.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToSayNoWithoutLosingPeople: Product = {
  slug: '10-ways-to-say-no-without-losing-people',
  title: '10 Ways to Say No Without Losing People',
  tagline: 'Most people do not have a boundary problem. They have a sentence problem. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Say-No-Without-Losing-People.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToStopBeingTiredAllTheTime: Product = {
  slug: '10-ways-to-stop-being-tired-all-the-time',
  title: '10 Ways to Stop Being Tired All the Time',
  tagline: 'Nine habits — and the one blood test no routine replaces. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Stop-Being-Tired-All-the-Time.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToStopBeingUnderpaid: Product = {
  slug: '10-ways-to-stop-being-underpaid',
  title: '10 Ways to Stop Being Underpaid',
  tagline: 'The negotiation is mostly over before the conversation starts. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Stop-Being-Underpaid.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const guide10WaysToWriteSoPeopleActuallyReadIt: Product = {
  slug: '10-ways-to-write-so-people-actually-read-it',
  title: '10 Ways to Write So People Actually Read It',
  tagline: 'Nobody is reading carefully. Write for the reader you have. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['10-Ways-to-Write-So-People-Actually-Read-It.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const whatYourScreentimeCostsYou: Product = {
  slug: 'what-your-screentime-costs-you',
  title: 'What Your Screentime Costs You',
  tagline: 'Open your screentime screen. Multiply by 52. 20 pages: what the reels sell vs what actually works, ten items with the smallest version and the mistake, a 90-day protocol, what NOT to do, and three printable sheets.',
  price: 499,
  pageCount: 20,
  trackerCount: 3,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 1,
  featured: true,
  longDescription: [],
  bulletPoints: [],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [{ filename: '1-cover-thumbnail.png', role: 'cover', alt: 'Product cover.' }],
  deliveryFiles: ['What-Your-Screentime-Costs-You.pdf'],
  setSlug: 'the-ten-series-full-set',
};

export const theTenSeriesGuides: Product[] = [
  guide10MoneyHabitsThatActuallyCompound,
  guide10ThingsBodyLanguageActuallyTellsYou,
  guide10WaysToActuallyBecomeAnEarlyRiser,
  guide10WaysToBeDangerouslyDisciplined,
  guide10WaysToBeDangerouslyHardToKill,
  guide10WaysToBeDangerouslyLikeable,
  guide10WaysToBeDangerouslySmart,
  guide10WaysToBeDangerouslyUnbothered,
  guide10WaysToBeGoodAtBeingAlone,
  guide10WaysToBeImpossibleToManipulate,
  guide10WaysToBeTakenSeriouslyBeforeYoure25,
  guide10WaysToBeUnforgettableInSixtySeconds,
  guide10WaysToBuildConfidenceThatIsReal,
  guide10WaysToGetDangerouslyLucky,
  guide10WaysToHaveADangerouslyGoodMemory,
  guide10WaysToLearnAnythingFaster,
  guide10WaysToNeverLoseYourTemper,
  guide10WaysToReadPeople,
  guide10WaysToSayNoWithoutLosingPeople,
  guide10WaysToStopBeingTiredAllTheTime,
  guide10WaysToStopBeingUnderpaid,
  guide10WaysToWriteSoPeopleActuallyReadIt,
  whatYourScreentimeCostsYou,
];

export const theTenSeriesFullSet: Product = {
  slug: 'the-ten-series-full-set',
  title: 'The Ten Series — All 23 Guides',
  tagline: 'Twenty-three of the internet\'s biggest hooks, taken seriously and priced honestly. 460 designed pages, 69 printable sheets, one payment, lifetime access.',
  price: 2999,
  anchorPrice: 11477,
  pageCount: 460,
  trackerCount: 69,
  accent: THE_TEN_SERIES.accent,
  category: THE_TEN_SERIES,
  format: 'PDF',
  fileCount: 2,
  longDescription: [
    {
      heading: 'EVERY REEL PROMISES 30 DAYS.',
      paragraphs: [
        'Not one of them tells you the real number.',
        '"Fluent in three months" is 600+ hours. "Lucid dream tonight" is roughly one night in six after weeks of practice. "Learn to code in 30 days" is 500–1,000 hours to employable. Every one of those things is genuinely reachable — just at the real price, which nobody selling you the 30-day version has any interest in saying.',
        'This is 23 guides that give you the real price. And the real method, and the page every reel skips.',
      ],
    },
    {
      heading: 'WHAT IS IN IT',
      paragraphs: [
        'Body and odds — Dangerously Hard to Kill · Stop Being Tired All the Time · Actually Become an Early Riser',
        'Thinking — Dangerously Smart · Learn Anything Faster · Dangerously Good Memory',
        'Running yourself — Dangerously Disciplined · Dangerously Unbothered · Never Lose Your Temper · Build Confidence That Is Real',
        'Other people — Dangerously Likeable · Unforgettable in Sixty Seconds · Say No Without Losing People · Good at Being Alone',
        'Not being taken advantage of — Read People · Impossible to Manipulate · What Body Language Actually Tells You',
        'Work and money — Taken Seriously Before You\'re 25 · Write So People Actually Read It · Stop Being Underpaid · Money Habits That Actually Compound · Dangerously Lucky',
        'And the opener — What Your Screentime Costs You',
      ],
    },
    {
      heading: 'A FEW OF THE ACTUAL ANSWERS',
      paragraphs: [
        'A ₹2,000 helmet worn strapped is a bigger contribution to being hard to kill than every ice bath, fast and gym session combined. For your age group, that is just what the numbers say.',
        'If you have been tired for months, get the blood test before the morning routine. Anaemia, B12, thyroid and blood sugar do not respond to discipline, and all four are cheap to check.',
        'Crossed arms does not mean defensive. "93% of communication is non-verbal" is a misquote of a narrow study. And nobody — including trained professionals — can detect lies by watching a face.',
        'Discipline is not willpower. It is deciding on Sunday so Wednesday-you does not get a vote.',
        'Confidence is not a feeling you talk yourself into. It is a written record of things you did while uncomfortable.',
      ],
    },
    {
      heading: 'WHAT THESE ARE NOT',
      paragraphs: [
        'General information for adults. Nothing here is medical, psychological, legal, financial, investment, educational or career advice. No product, insurer, scheme, app, course, employer or platform is named or endorsed. No outcome of any kind is promised.',
        'Where a popular claim has replicated poorly, these books say so instead of repeating it. That is the entire point of the line.',
      ],
    },
  ],
  bulletPoints: [
    '23 guides, 20 designed pages each, 460 pages total',
    '69 printable sheets across the set',
    'What the reels sell vs what actually works, in every guide',
    'Ten items each, with the smallest version and the common mistake',
    'A 90-day protocol and a WHAT NOT TO DO page in every guide',
    'No product, app or platform named or endorsed',
    'Instant download · One payment · Lifetime access',
  ],
  faqs: TEN_SERIES_FAQS,
  disclaimer: TEN_SERIES_DISCLAIMER,
  helplines: [],
  tags: ['the ten series', 'honest self improvement'],
  gallery: [
    {
      filename: '1-cover-thumbnail.png',
      role: 'cover',
      alt: 'The Ten Series cover: twenty-three viral hooks, taken seriously.',
    },
  ],
  deliveryFiles: ['The-Ten-Series.zip', 'START-HERE.txt'],
};

/** All twenty-three individual guides plus the full-set product, in filename order. */
export const allTheTenSeriesProducts: Product[] = [...theTenSeriesGuides, theTenSeriesFullSet];
